# Generated by Django 4.2 on 2025-07-11 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_tasktimeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10),
        ),
    ]
